### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by Avamander** [emersion/maddy#72] opened 2019-05-23 00:34 UTC
Just wanted to ask, is there a way to specify that Maddy would serve the right cert based on SNI when using TLS?

**Comment by foxcpp** [comment] 2019-05-23 04:46
What is your use case? We were talking about it in #58 but decided to leave it out at least for now.

**Comment by foxcpp** [comment] 2019-05-23 04:50
Duplicate of #58.

**Closed by foxcpp** 2019-05-23 04:50 UTC

**Comment by Avamander** [comment] 2019-05-24 21:24
Given that MTA-STS is a thing it would be nice to have support for multi-tenant systems for those cases as well.
